"""add is_saved to recommendations

Revision ID: 6cf7c27982fc
Revises: 316c70731106
Create Date: 2026-07-17 13:44:12.272250

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cf7c27982fc"
down_revision: str | None = "316c70731106"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recommendations",
        sa.Column("is_saved", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recommendations", "is_saved")
    # ### end Alembic commands ###
