"""initial_schema

Revision ID: 81d27c6359d2
Revises: 
Create Date: 2026-07-17 00:26:12.988182

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "81d27c6359d2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table(
        "education_content",
        sa.Column(
            "related_strategy",
            sa.Enum(
                "CONTINUOUS_FLOODING",
                "CONTINUOUS_FLOODING_MODIFIED",
                "AWD_MILD",
                "AWD_STRICT",
                "DELAYED_IRRIGATION",
                "PARTIAL_IRRIGATION",
                name="irrigation_strategy",
            ),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body_markdown", sa.Text(), nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_education_content")),
    )
    op.create_table(
        "regional_climate_baseline",
        sa.Column("province_code", sa.String(length=10), nullable=False),
        sa.Column("avg_daily_rainfall_mm", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("avg_temperature_c", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("avg_et0_mm", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regional_climate_baseline")),
        sa.UniqueConstraint(
            "province_code", name=op.f("uq_regional_climate_baseline_province_code")
        ),
    )
    op.create_table(
        "rice_varieties",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("total_duration_days", sa.Integer(), nullable=False),
        sa.Column(
            "phase_breakdown_percent", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_duration_days > 0", name=op.f("ck_rice_varieties_total_duration_days_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rice_varieties")),
        sa.UniqueConstraint("code", name=op.f("uq_rice_varieties_code")),
    )
    op.create_table(
        "users",
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_active_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where="deleted_at IS NULL AND email IS NOT NULL",
    )
    op.create_index(
        "uq_users_active_phone_number",
        "users",
        ["phone_number"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "fields",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column(
            "soil_type", sa.Enum("SANDY", "LOAM", "CLAY", "SILTY", name="soil_type"), nullable=False
        ),
        sa.Column("rice_variety_id", sa.UUID(), nullable=False),
        sa.Column("planting_date", sa.Date(), nullable=False),
        sa.Column("field_area_ha", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "previous_irrigation_method",
            postgresql.ENUM(
                "CONTINUOUS_FLOODING",
                "CONTINUOUS_FLOODING_MODIFIED",
                "AWD_MILD",
                "AWD_STRICT",
                "DELAYED_IRRIGATION",
                "PARTIAL_IRRIGATION",
                name="irrigation_strategy",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "irrigation_system_type",
            sa.Enum(
                "TECHNICAL",
                "SEMI_TECHNICAL",
                "RAINFED",
                "COMMUNAL_GRAVITY",
                name="irrigation_system_type",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "field_area_ha > 0 AND field_area_ha <= 25",
            name=op.f("ck_fields_field_area_ha_valid_range"),
        ),
        sa.CheckConstraint(
            "latitude BETWEEN -11.00 AND 6.10", name=op.f("ck_fields_latitude_indonesia_range")
        ),
        sa.CheckConstraint(
            "longitude BETWEEN 94.70 AND 141.10", name=op.f("ck_fields_longitude_indonesia_range")
        ),
        sa.ForeignKeyConstraint(
            ["rice_variety_id"],
            ["rice_varieties.id"],
            name=op.f("fk_fields_rice_variety_id_rice_varieties"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_fields_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fields")),
    )
    op.create_index("idx_fields_location", "fields", ["latitude", "longitude"], unique=False)
    op.create_index(
        "idx_fields_user_id",
        "fields",
        ["user_id"],
        unique=False,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("whatsapp_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "recommendation_change_alert", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("weather_risk_alert", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notification_preferences_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preferences")),
        sa.UniqueConstraint("user_id", name=op.f("uq_notification_preferences_user_id")),
    )
    op.create_table(
        "weather_snapshots",
        sa.Column("field_id", sa.UUID(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("et0_mm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("is_estimated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("estimation_reason", sa.String(length=100), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["field_id"], ["fields.id"], name=op.f("fk_weather_snapshots_field_id_fields")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_snapshots")),
    )
    op.create_index(
        "idx_weather_snapshots_field_id_fetched_at",
        "weather_snapshots",
        ["field_id", sa.text("fetched_at DESC")],
        unique=False,
    )
    op.create_table(
        "recommendations",
        sa.Column("field_id", sa.UUID(), nullable=False),
        sa.Column("weather_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "recommended_strategy",
            postgresql.ENUM(
                "CONTINUOUS_FLOODING",
                "CONTINUOUS_FLOODING_MODIFIED",
                "AWD_MILD",
                "AWD_STRICT",
                "DELAYED_IRRIGATION",
                "PARTIAL_IRRIGATION",
                name="irrigation_strategy",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("engine_type", sa.String(length=20), nullable=False),
        sa.Column("model_version", sa.String(length=30), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score BETWEEN 0 AND 1",
            name=op.f("ck_recommendations_confidence_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["field_id"], ["fields.id"], name=op.f("fk_recommendations_field_id_fields")
        ),
        sa.ForeignKeyConstraint(
            ["weather_snapshot_id"],
            ["weather_snapshots.id"],
            name=op.f("fk_recommendations_weather_snapshot_id_weather_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    op.create_index(
        "idx_recommendations_field_id_created_at",
        "recommendations",
        ["field_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("field_id", sa.UUID(), nullable=False),
        sa.Column("recommendation_id", sa.UUID(), nullable=True),
        sa.Column("channel", sa.String(length=20), server_default="whatsapp", nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "delivery_status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["field_id"], ["fields.id"], name=op.f("fk_notifications_field_id_fields")
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_notifications_recommendation_id_recommendations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "idx_notifications_user_id_created_at",
        "notifications",
        ["user_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "recommendation_predictions",
        sa.Column("recommendation_id", sa.UUID(), nullable=False),
        sa.Column("water_saving_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("expected_yield_ton_per_ha", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("yield_baseline_ton_per_ha", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("ch4_reduction_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("n2o_change_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("net_gwp_reduction_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_recommendation_predictions_recommendation_id_recommendations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_predictions")),
        sa.UniqueConstraint(
            "recommendation_id", name=op.f("uq_recommendation_predictions_recommendation_id")
        ),
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table_name in (
        "users",
        "notification_preferences",
        "rice_varieties",
        "fields",
        "education_content",
    ):
        op.execute(
            f"CREATE TRIGGER trg_{table_name}_updated_at "
            f"BEFORE UPDATE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in (
        "education_content",
        "fields",
        "rice_varieties",
        "notification_preferences",
        "users",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_updated_at ON {table_name}")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    op.drop_table("recommendation_predictions")
    op.drop_index("idx_notifications_user_id_created_at", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("idx_recommendations_field_id_created_at", table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index("idx_weather_snapshots_field_id_fetched_at", table_name="weather_snapshots")
    op.drop_table("weather_snapshots")
    op.drop_table("notification_preferences")
    op.drop_index("idx_fields_user_id", table_name="fields", postgresql_where="deleted_at IS NULL")
    op.drop_index("idx_fields_location", table_name="fields")
    op.drop_table("fields")
    op.drop_index(
        "uq_users_active_phone_number", table_name="users", postgresql_where="deleted_at IS NULL"
    )
    op.drop_index(
        "uq_users_active_email",
        table_name="users",
        postgresql_where="deleted_at IS NULL AND email IS NOT NULL",
    )
    op.drop_table("users")
    op.drop_table("rice_varieties")
    op.drop_table("regional_climate_baseline")
    op.drop_table("education_content")
    op.execute("DROP TYPE IF EXISTS irrigation_system_type")
    op.execute("DROP TYPE IF EXISTS soil_type")
    op.execute("DROP TYPE IF EXISTS irrigation_strategy")
    # ### end Alembic commands ###
